/*
 * Copyright (c) 2023 Pantacor Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

#include "init.h"
#include "daemons.h"
#include "tsh.h"
#include "utils/fs.h"

#define MODULE_NAME "daemons"
#define pv_log(level, msg, ...)                                                \
	vlog(MODULE_NAME, level, "(%s:%d) " msg, __FUNCTION__, __LINE__,       \
	     ##__VA_ARGS__)
#include "log.h"

struct pv_init_daemon daemons[] = {
	{ "hwrngd", 0, 1, "/usr/bin/rngd", "/usr/bin/rngd -f",
	  DM_EMBEDDED | DM_STANDALONE, 0 },
#ifdef PANTAVISOR_XCONNECT
	{ "pv-xconnect", 0, 1, "/usr/bin/pv-xconnect", "/usr/bin/pv-xconnect",
	  DM_ALL, 0 },
#endif
#ifdef PANTAVISOR_XCONNECT_DBUS_SYSTEMBUS
	// No --system: that is shorthand for --config-file=.../system.conf and
	// would conflict with our generated --config-file. Our config declares
	// <type>system</type>, so this is still a system bus.
	{ PV_DBUS_SYSTEMBUS_DAEMON, 0, 1, "/usr/bin/dbus-daemon",
	  "/usr/bin/dbus-daemon --nofork --nopidfile --config-file=" PV_DBUS_SYSTEMBUS_CONF,
	  DM_ALL, 0 },
#endif
	{ 0, 0, 0, 0, 0, 0, 0 }
};

static int daemon_spawn(struct pv_init_daemon *self)
{
	self->pid = 0;
	pv_log(INFO, "Spawning %s daemon.", self->name);
	if (self->_respawning) {
		pv_log(INFO, "... deferring respawn by 5 seconds");
		self->pid = tsh_run("/bin/sleep 5", 0, 0);
		self->_respawning = 0;
	} else {
#ifndef DISABLE_LOGSERVER
		char out_name[64], err_name[64];
		snprintf(out_name, sizeof(out_name), "%s-out", self->name);
		snprintf(err_name, sizeof(err_name), "%s-err", self->name);
		self->pid =
			tsh_run_daemon_logserver(self->cmd, out_name, err_name);
#else
		self->pid = tsh_run(self->cmd, 0, 0);
#endif
		self->_respawning = 1;
	}
	if (self->pid < 0) {
		pv_log(ERROR, "error forking child: '%s': %s", self->name,
		       strerror(errno));
		return self->pid;
	}

	return self->pid;
}

struct pv_init_daemon *pv_init_get_daemons(void)
{
	return daemons;
}

int pv_init_spawn_daemons(init_mode_t mode)
{
	int i = 0;
	struct stat sb;
	unsigned int mode_flag = (1 << mode);

	sigset_t blocked_sig, old_sigset;
	sigemptyset(&blocked_sig);
	sigaddset(&blocked_sig, SIGCHLD);
	sigprocmask(SIG_BLOCK, &blocked_sig, &old_sigset);

	for (i = 0; daemons[i].name; i++) {
		if (daemons[i].pid > 0 || !daemons[i].respawn)
			continue;
		// skip daemons not enabled for this init mode
		if (!(daemons[i].modes & mode_flag)) {
			pv_log(DEBUG, "daemon %s not enabled for init mode %d",
			       daemons[i].name, mode);
			continue;
		}

		pv_log(INFO, "enabling daemon: %s", daemons[i].name);

		if (stat(daemons[i].testpath, &sb)) {
			pv_log(INFO, "daemon not found %s: disabling respawn",
			       daemons[i].name);
			daemons[i].pid = 0;
			daemons[i].respawn = 0;
			continue;
		}

		daemons[i].pid = daemon_spawn(&daemons[i]);

		pv_log(INFO, "spawned daemon %s: %d", daemons[i].name,
		       daemons[i].pid);
	}
	sigprocmask(SIG_SETMASK, &old_sigset, NULL);
	return 0;
}

int pv_init_is_daemon(pid_t pid)
{
	int i = 0;
	while (daemons[i].name) {
		if (daemons[i].pid == pid)
			return 1;
		i++;
	}
	return 0;
}

int pv_init_daemon_exited(pid_t pid)
{
	int i = 0;
	while (daemons[i].name) {
		if (daemons[i].pid == pid)
			daemons[i].pid = daemons[i].respawn ? 0 : -1;
		i++;
	}
	return 0;
}

void pv_init_stop_daemons(void)
{
	int i = 0;
	while (daemons[i].name) {
		if (daemons[i].pid > 0) {
			pv_log(INFO, "Stopping daemon %s (pid %d)",
			       daemons[i].name, daemons[i].pid);
			daemons[i].respawn = 0;
			kill(daemons[i].pid, SIGTERM);
		}
		i++;
	}
}

#ifdef PANTAVISOR_XCONNECT_DBUS_SYSTEMBUS
// Default-deny base policy for the hosted system bus. Per-name allow rules are
// generated by pantavisor into PV_DBUS_SYSTEMBUS_POLICYDIR from the owns/allow
// declarations in container service manifests (see state.c). Rules are matched
// in order, last match wins: method calls and name ownership are denied by
// default and only re-granted by the generated per-uid fragments; calls to the
// bus driver, replies and signals stay allowed so peers can connect and reply.
static const char dbus_systembus_base_conf[] =
	"<!DOCTYPE busconfig PUBLIC "
	"\"-//freedesktop//DTD D-Bus Bus Configuration 1.0//EN\" "
	"\"http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd\">\n"
	"<busconfig>\n"
	"  <type>system</type>\n"
	"  <listen>unix:path=" PV_DBUS_SYSTEMBUS_SOCKET "</listen>\n"
	"  <auth>EXTERNAL</auth>\n"
	"\n"
	"  <policy context=\"default\">\n"
	"    <allow user=\"*\"/>\n"
	"    <deny own=\"*\"/>\n"
	"    <deny send_type=\"method_call\"/>\n"
	"    <allow send_destination=\"org.freedesktop.DBus\"/>\n"
	"    <allow receive_sender=\"org.freedesktop.DBus\"/>\n"
	"    <allow send_requested_reply=\"true\" send_type=\"method_return\"/>\n"
	"    <allow send_requested_reply=\"true\" send_type=\"error\"/>\n"
	"    <allow receive_requested_reply=\"true\" receive_type=\"method_return\"/>\n"
	"    <allow receive_requested_reply=\"true\" receive_type=\"error\"/>\n"
	"    <allow send_type=\"signal\"/>\n"
	"    <allow receive_type=\"signal\"/>\n"
	"  </policy>\n"
	"\n"
	"  <includedir>" PV_DBUS_SYSTEMBUS_POLICYDIR "</includedir>\n"
	"</busconfig>\n";

// Gate the hosted dbus-daemon on the runtime config entry (defaults to true
// when built in) and lay down its runtime dir + base config before spawn.
static void dbus_systembus_prepare(void)
{
	if (!pv_config_get_bool(PV_XCONNECT_DBUS_SYSTEMBUS_ENABLED)) {
		pv_log(INFO,
		       "hosted dbus system bus disabled via config, not starting %s",
		       PV_DBUS_SYSTEMBUS_DAEMON);
		for (int i = 0; daemons[i].name; i++) {
			if (!strcmp(daemons[i].name,
				    PV_DBUS_SYSTEMBUS_DAEMON)) {
				daemons[i].respawn = 0;
				daemons[i].pid = -1;
			}
		}
		return;
	}

	if (pv_fs_mkdir_p(PV_DBUS_SYSTEMBUS_POLICYDIR, 0755)) {
		pv_log(ERROR, "could not create %s: %s",
		       PV_DBUS_SYSTEMBUS_POLICYDIR, strerror(errno));
		return;
	}

	FILE *f = fopen(PV_DBUS_SYSTEMBUS_CONF, "w");
	if (!f) {
		pv_log(ERROR, "could not write %s: %s", PV_DBUS_SYSTEMBUS_CONF,
		       strerror(errno));
		return;
	}
	fputs(dbus_systembus_base_conf, f);
	fclose(f);

	pv_log(INFO, "hosted dbus system bus enabled, base config at %s",
	       PV_DBUS_SYSTEMBUS_CONF);
}
#endif

static int pv_daemons_init(struct pv_init *this)
{
	init_mode_t mode = pv_config_get_system_init_mode();

#ifdef PANTAVISOR_XCONNECT_DBUS_SYSTEMBUS
	dbus_systembus_prepare();
#endif

	pv_init_spawn_daemons(mode);

	return 0;
}

struct pv_init pv_init_daemons = {
	.init_fn = pv_daemons_init,
	.flags = 0,
};
