#!/bin/sh

usage() {

	echo "CMD [options] <outdir>" 
	echo " -c <corelimit %c>"
	echo " -d <mode %d>"
	echo " -e <comm %e>"
	echo " -E <path %E"
	echo " -g <real GID %g>"
	echo " -h <hostname %h>"
	echo " -i <TID in pidns %i>"
	echo " -I <TID in hostns %I>"
	echo " -p <PID in pidns %p>"
	echo " -P <PID in hostns %P"
	echo " -s <signal crashed %s>"
	echo " -t <timeofdump %t>"
	echo " -u <uid %u"

	echo ""
	echo "See: core(5) manpage for details"
}

ensure() {
	if [ -z "$2" ]; then
		echo "ERROR: missing $1 parameter; see usage"
		usage
		exit 125
	fi
}


while [ -n "$1" ]; do
	case $1 in
		--skip)
			echo "SKIPPING core dump processing as requested."
			exit 0
			;;
		-c)
			shift; corelimit=$1; ensure corelimit "$corelimit"
			;;
		-d)
			shift; mode=$1; ensure mode "$mode"
			;;
		-e)
			shift; comm=$1; ensure comm "$comm"
			;;
		-E)
			shift; path=$1; ensure path "$path"
			;;
		-g)
			shift; realgid=$1; ensure realgid "$realgid"
			;;
		-h)
			shift; hostname=$1; ensure hostname "$hostname"
			;;
		-i)
			shift; tidns=$1; ensure tidns "$tidns"
			;;
		-I)
			shift; tid=$1; ensure tid "$tid"
			;;
		-p)
			shift; pidns=$1; ensure pidns "$pidns"
			;;
		-P)
			shift; pid=$1; ensure pid "$pid"
			;;
		-s)
			shift; signal=$1; ensure signal "$signal"
			;;
		-t)
			shift; timeofdump=$1; ensure timeofdump "$timeofdump"
			;;
		-u)
			shift; uid=$1; ensure uid "$uid"
			;;
		--help)
			usage
			exit 123
			;;
		*)
			outdir=$1; ensure outdir "$outdir"
			;;
	esac
	shift
done

ensure outdir "$outdir"
mkdir -p "$outdir"

dump_crash() {

	fname=$outdir/pvcrash.1.crash
	mname=$fname.manifest
	if [ -f "$fname" ]; then
		echo "not overwriting existing crash; delete it first."
		exit 2
	fi

	{
		echo "corelimit: $corelimit"
		echo "mode: $mode"
		echo "comm: $comm"
		echo "path: $path"
		echo "realgid: $realgid"
		echo "hostname: $hostname"
		echo "tidns: $tidns"
		echo "pidns: $pidns"
		echo "pid: $pid"
		echo "signal: $signal"
		echo "timeofdump: $timeofdump"
		echo "uid: $uid"
	} > "$mname"

	# cat the coredump to fname
	cat > "$fname"
}

dump_crash

