name: 'Build Pantavisor'

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      configs:
        required: true
        type: string

jobs:
  build-kas:
    runs-on: ["self-hosted"]
    container:
      image: ghcr.io/pantacor/kas/kas:next-v7
      volumes:
        - shared:/shared

    steps:
      - name: checkout meta-pantavisor repo
        uses: actions/checkout@v4
        with:
          repository: 'pantacor/meta-pantavisor'
          path: 'meta-pantavisor'

      - name: shared
        run: |
          mkdir -p /shared/sstate
          chown builder:builder /shared/sstate
          mkdir -p /shared/dldir
          chown builder:builder /shared/dldir

      - name: Build Pantavisor
        run: su - builder -c "
          cd $GITHUB_WORKSPACE/meta-pantavisor &&
          env &&
          kas checkout ${{ inputs.configs }} &&
          . layers/poky/oe-init-build-env &&
          devtool modify pantavisor &&
          cd build/workspace/sources/pantavisor &&
          git checkout ${{ github.sha }} &&
          bitbake pantavisor-starter
          "

      - name: chmod
        run: chmod -R 777 $GITHUB_WORKSPACE

      - name: Prepare Artifacts for Upload
        run: |
          cp meta-pantavisor/build/tmp-*/deploy/images/*/pantavisor-starter*.wic.* .
          cp meta-pantavisor/build/tmp-*/deploy/images/*/*pvrexport.* .

      - name: Archive image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pantavisor-starter-${{ inputs.name }}
          path: pantavisor-starter*.wic.*

      - name: Archive bsp artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pantavisor-bsp-${{ inputs.name }}
          path: 'pantavisor-bsp*pvrexport.tgz'

      - name: Archive containers artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pvrexports-${{ inputs.name }}
          path: '*pvrexport*'
