name: 'Orangepi 3 LTS'

on:
  workflow_call:

jobs:

  build-sunxi-orange-pi-3lts-scarthgap:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/sunxi-orange-pi-3lts-scarthgap.yaml:.github/configs/shared-vols.yaml
      name: sunxi-orange-pi-3lts-scarthgap
    secrets: inherit
