name: 'On push: build targets'

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'

jobs:

  raspberrypi-armv8-glibc-scarthgap:
    uses: ./.github/workflows/build-pantavisor-bsp.yaml
    with:
      # meta-pantavisor
      configs: .github/configs/shared-vols.yaml:.github/configs/release/raspberrypi-armv8-scarthgap.yaml
      name: raspberrypi-armv8-glibc

  raspberrypi-armv8-musl-scarthgap:
    uses: ./.github/workflows/build-pantavisor-bsp.yaml
    with:
      # meta-pantavisor
      configs: .github/configs/shared-vols.yaml:.github/configs/release/raspberrypi-armv8-scarthgap.yaml:.github/configs/musl.yaml
      name: raspberrypi-armv8-musl

  raspberrypi-armv8-musl-pantavisor:
    uses: ./.github/workflows/build-pantavisor.yaml
    with:
      # meta-pantavisor
      configs: .github/configs/shared-vols.yaml:.github/configs/release/raspberrypi-armv8-scarthgap.yaml
      name: raspberrypi-armv8