name: Trigger Docs Update

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/trigger-docs.yaml'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI
        run: |
          curl --request POST \
            --form token=${{ secrets.GITLAB_DOCS_TRIGGER_TOKEN }} \
            --form ref=master \
            --form "variables[TRIGGER_SOURCE]=pantavisor" \
            https://gitlab.com/api/v4/projects/pantacor%2Fdocs/trigger/pipeline
